### ISSUE TITLE
Nu merge pe ac mane

### ISSUE THREAD

**Issue by ksenonadv** [Stickey21/Stealth-Remastered#10]
![hbKGmX2](https://user-images.githubusercontent.com/25392951/112130038-b4572300-8bd0-11eb-9da4-689f95a70269.png)
dc nu merge citu ..
aveam ancredere an voi

**Comment by Stickey21** [comment]
Eu zic ca a mers s0bu
https://youtu.be/MNRr47bSOl8

**Comment by Stickey21** [comment]
Update:
https://www.youtube.com/watch?v=LMR_ZvBoq8Y

**Comment by Stickey21** [comment]
Update:
https://www.youtube.com/watch?v=gdxW1lHfqVM

**Comment by Stickey21** [comment]
Update:
https://www.youtube.com/watch?v=zZ882ipzUV4

**Comment by Stickey21** [comment]
stefane, iar merge s0bu
https://www.youtube.com/watch?v=f52fOK5hgQ8
